#' Density of the Borel distribution
#'
#' @param x Vector of quantiles; integer.
#' @param mu mu parameter (the poisson mean); non-negative.
#' @param log Logical; if TRUE, probabilities p are given as log(p).
#'
#' @return Probability mass.
#'
#' @author Sebastian Funk
#' @export
dborel <- function(x, mu, log = FALSE) {
  checkmate::assert_numeric(
    x, lower = 1L, upper = Inf
  )
  checkmate::assert_number(
    mu, lower = 0L, finite = TRUE, na.ok = FALSE
  )

  if (x < 1L) stop("'x' must be greater than 0.")
  ld <- -mu * x + (x - 1L) * log(mu * x) - lgamma(x + 1L)
  if (!log) ld <- exp(ld)
  return(ld)
}

#' Generate random numbers from the Borel distribution
#'
#' Random numbers are generated by simulating from a Poisson branching process
#' @param n Number of random variates to generate.
#' @inheritParams dborel
#' @param infinite Any number to treat as infinite; simulations will be
#'     stopped if this number is reached
#'
#' @return Vector of random numbers
#' @author Sebastian Funk
#' @export
rborel <- function(n, mu, infinite = Inf) {
  checkmate::assert_number(
    n, lower = 1L, finite = TRUE, na.ok = FALSE
  )
  checkmate::assert_number(
    mu, lower = 0L, finite = TRUE, na.ok = FALSE
  )
  # Run simulations
  simulate_summary(
    ntrees         = n,
    offspring_dist = "pois",
    statistic      = "size",
    stat_max       = infinite,
    lambda         = mu
  )
}
